name: vyra
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.9.0
  either_dart: ^1.0.0
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  geolocator: ^14.0.2
  geotypes: ^0.0.2
  get_it: ^8.2.0
  hydrated_bloc: ^10.1.1
  intl: ^0.20.2
  location: ^8.0.1
  path_provider: ^2.1.5
  share_plus: ^12.0.0
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1
  url_launcher: ^6.3.2
  flutter_localization: ^0.3.3
  flutter_dotenv: ^6.0.0
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^19.4.2
  permission_handler: ^12.0.1
  rxdart: ^0.28.0
  freezed_annotation: ^2.4.4
  package_info_plus: ^8.3.1
  mapbox_maps_flutter: ^2.11.0
  lottie: ^3.1.2
  mobkit_dashed_border: ^0.0.8
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.0
  hive_generator: ^2.0.1
  freezed: ^2.5.7

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/illustrations/language/
    - assets/illustrations/notification/
    - assets/illustrations/location/
    - assets/illustrations/theme/
    - assets/images/logo/
    - assets/images/flags/
    - assets/images/onboarding/
    - assets/fonts/

  fonts:
    - family: InterTight
      fonts:
        - asset: assets/fonts/InterTight-Black.ttf
        - asset: assets/fonts/InterTight-Bold.ttf
        - asset: assets/fonts/InterTight-ExtraBold.ttf
        - asset: assets/fonts/InterTight-ExtraLight.ttf
        - asset: assets/fonts/InterTight-Light.ttf
        - asset: assets/fonts/InterTight-Medium.ttf
        - asset: assets/fonts/InterTight-Regular.ttf
        - asset: assets/fonts/InterTight-SemiBold.ttf
        - asset: assets/fonts/InterTight-Thin.ttf
